### ISSUE TITLE
Specify private key using upload.sh

### ISSUE THREAD

**Issue by acrogenesis** [nerves-project/nerves_firmware_ssh#17]
Is there a way to specify the ssh key to use?

**Comment by fhunleth** [comment]
The upload script calls commandline `ssh`. You could either modify the script to pass additional arguments to `ssh` or specify the key in your `.ssh/config`. For the latter, I think that the configuration text is something like:

```
Host nerves.local
    IdentityFile ~/.ssh/my_firmware_update_key_id_rsa
```

**Comment by acrogenesis** [comment]
Thanks I went ahead and edited the `upload.sh`
