### ISSUE TITLE
Using default firmware.gen.script exits 255 (but upload succeeds)

### ISSUE THREAD

**Issue by jjcarstens** [nerves-project/nerves_firmware_ssh#19]
Porting [this forum question](
https://elixirforum.com/t/using-default-firmware-gen-script-exits-255-even-though-upload-is-successful/15677/2) over to an issue for tracking.

I started with forum thinking it would just be configuration problem but according to @fhunleth it is actually a problem of `nerves_firmware_ssh` not returning the status.

**Comment by jjcarstens** [comment]
Frank opted to make a PR, but I’d love to look it over and attempt the fix if that’s cool. (Feel free to override me if you just want to get it done quick)

**Comment by fhunleth** [comment]
Oh no, I missed your comment and just went ahead and PR'd the change I made last night after cleaning it up. https://github.com/nerves-project/nerves_firmware_ssh/pull/20

So sorry! I promise that there are more bugs and I won't deprive you of the satisfaction of fixing issues again.
