### ISSUE TITLE
Upgrading to elixir (from 1.6.6/OTP20) 1.7.3/otp 21 fails to load crypto.so at runtime

### ISSUE THREAD

**Issue by TobiG77** [nerves-project/nerves_firmware_ssh#25]
* Elixir version (`elixir -v`):

Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.7.3 (compiled with Erlang/OTP 21)

* Nerves environment: (`mix nerves.env --info`)
|nerves_bootstrap| Environment Package List

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.5.0
  Type:        toolchain_platform
  BuildRunner: nil

  Pkg:         nerves_system_br
  Vsn:         1.4.1
  Type:        system_platform
  BuildRunner: nil

  Pkg:         nerves_system_rpi3
  Vsn:         1.3.0
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Docker, []}

  Pkg:         nerves_toolchain_arm_unknown_linux_gnueabihf
  Vsn:         1.1.0
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

|nerves_bootstrap| Loadpaths Start

Nerves environment
  MIX_TARGET:   rpi3
  MIX_ENV:      dev

|nerves_bootstrap| Environment Variable List
  target:     rpi3
  toolchain:  ~/.nerves/artifacts/nerves_toolchain_arm_unknown_linux_gnueabihf-darwin_x86_64-1.1.0
  system:     ~/.nerves/artifacts/nerves_system_rpi3-portable-1.3.0
  app:        ~/code/sapient/camnet/nerves_neuron

Other details:

attempted fixes so far, completely clean deps and build, upgrade all dependencies, rinse repeat 

### Current behavior

Startup of nerves fails with: 
'Unable to load crypto library. Failed with error"
:load_failed, Failed to load NIF library: '/srv/erlang/lib/crypto-4.3.2/priv/lib/crypto.so: invalid ELF header\''}}
OpenSSL might not be installed on this system

### Expected behavior

nerves_firmware_ssh starts up normal

**Comment by TobiG77** [comment]
Quick update, when attempting to replicate the issue in a brand new nerves project, created with elixir 1.7.3 / otp 21 this issue does not occur. I'll keep digging ...


|nerves_bootstrap| Environment Package List

  Pkg:         nerves_system_br
  Vsn:         1.4.1
  Type:        system_platform
  BuildRunner: nil

  Pkg:         nerves_system_rpi3
  Vsn:         1.3.0
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Docker, []}

  Pkg:         nerves_toolchain_arm_unknown_linux_gnueabihf
  Vsn:         1.1.0
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.5.0
  Type:        toolchain_platform
  BuildRunner: nil

|nerves_bootstrap| Loadpaths Start


Nerves environment
  MIX_TARGET:   rpi3
  MIX_ENV:      dev

|nerves_bootstrap| Environment Variable List
  target:     rpi3
  toolchain:  ~/.nerves/artifacts/nerves_toolchain_arm_unknown_linux_gnueabihf-darwin_x86_64-1.1.0
  system:     ~/.nerves/artifacts/nerves_system_rpi3-portable-1.3.0
  app:        ~/code/sapient/nerves_firmware_ssh_test

**Comment by TobiG77** [comment]
I ran out of time looking into the root cause. The workaround is to simply move the code into a project created from scratch with latest erlang/otp + elixir. OTP ftw making this trivial.

**Comment by fhunleth** [comment]
Thanks for the update and for taking some time to try to figure out the root cause.

**Comment by cokron** [comment]
Hello Frank and Tobias, good to see you here :-)
I have run into the same issue. Any updates yet on how to fix this other than recreating project from scratch and copying all code into it? 
Me too, I switched from Erlang/OTP 20 to Erlang/OTP 21 and from Elixir 1.4 to 1.7. The error occurs, when shoehorn tries to use the crypto library.
I'll follow Tobias lead and recreate my project, so no need to fix this for me, but I guess others might run into the same issue.

**Comment by fhunleth** [comment]
I don't think there are any updates. I totally believe that it happens, but I haven't been able to reproduce it. It really seems like I have checks in `nerves_system_br` to catch this before runtime, but obviously something isn't working.
