### ISSUE TITLE
Update fails sometimes

### ISSUE THREAD

**Issue by fazibear** [nerves-project/nerves_firmware_ssh#26]
### Environment

* Elixir version (`elixir -v`): 1.7.3
* Nerves environment (`mix nerves.env --info`): 
* Additional information about your host, target hardware or environment that
  may help

This is an x86_64 PC with 64GB SSD

### Current behavior

We have very large images (about 600MB). Sometimes we archiving a serious error.
After a restart, the system does not boot. Sometimes it grub can't boot image, sometimes we get a decompression error.

It's really hard to debug. All I now that we're burning image od SSD, so it's a lot faster than the network. There is no way that packets are messed up during transfer.

Another option is flushing data to disk before the reboot. Don't know if it happening and when.  

### Expected behavior

Successful update all the time :)

**Comment by fhunleth** [comment]
There are production devices with images in the low 100s MB and I've done >3 GB images, so I'd hope that size is not the issue. 

When you get a decompression error, is that with the Linux kernel?

If you were to remove the SSD, connect it to another PC and look at the files that don't load, are they corrupt or truncated?

**Comment by fazibear** [comment]
This is great idea, once it happened once again, I'll connect ssd and try to verify what was written...

**Comment by fhunleth** [comment]
Please re-open if it happens again and there's more info.
