### ISSUE TITLE
Partial updates can corrupt the filesystem

### ISSUE THREAD

**Issue by trarbr** [nerves-project/nerves_firmware_ssh#44]
### Environment

* Elixir version (`elixir -v`): 1.8.1-opt-21 (asdf)
* Nerves environment: (`mix nerves.env --info`)
* Additional information about your host, target hardware or environment that
  may help

Using nerves_ssh_firmware version 0.4.3 on an x86-64 system and our firmware images are about 100MB in size.

### Current behavior

Sometimes, a partial upgrade followed by a full upgrade can result in filesystem corruption of the updated filesystem. The update is performed using the generated `upload.sh` script. Today is the first time we've seen this error, but we've been able to reproduce it like this:

1. Start a firmware upgrade with the upload.sh script, but cancel it early (0 - 10% complete).
2. Start a new firmware upgrade, and let it run to completion and reboot the device.

The outcome is not always the same. One time it ran until 2% completion, and this resulted in grub being unable to boot the system (it printed `error: unsupported gzip image`). Other times (about 4% complete), it would run into a squashfs error right after booting (`SQUASHFS error: "zlib decompression failed, data probably corrupt"`), just after erlinit started (but before our code started) - and if the partial upgrade was stopped at 7-10% completion, erlinit would boot our application, but then hit EXT4 errors.

Example session:

```shell
$> MIX_TARGET=... ./upload.sh 192.168.21.3
...
Uploading to 192.168.21.3...
Running fwup...
fwup: Upgrading partition B
|===                                 | 9% (9.15 / 101.50)^C
$> MIX_TARGET=... ./upload.sh 192.168.21.3
...
Uploading to 192.168.21.3...
Running fwup...
fwup: Upgrading partition B
|====================================| 100% (101.50 / 101.50) MB
```

### Expected behavior

After a full, successful upgrade, the filesystem should not be corrupted after rebooting, no matter if there have been previous, partial firmware upgrades.

### Notes

Rebooting after a partial upgrade and then doing full upgrade works well.

I digged into the code and found some clues. This is probably related to how the fwup processes are handled - on a new firmware upgrade, a new fwup process is started. If the update is cancelled, this fwup process keeps running (confirmed this by printing the `Nerves.Firmware.SSH.Fwup` PID in `init` and checking with `Process.alive?` that the fwup process is still running after SSH upgrade was cancelled). This only dies when the system is rebooted - at this time I see `fwup: Error sending Ctrl+Z as part of the exit handshake` printed to console.

So my current thinking is that the partially-complete fwup process actually exits after the fwup process which completes its upgrade - and that this partially-complete fwup process might flush something to disk at this point which breaks the upgrade. 

I've "confirmed" this by manually killing the partially-complete fwup process before doing the full upgrade. Maybe I was just lucky, so confirmed is left in quotes.

Not sure if any of this makes sense, let me know if I should try and explain it again  😂

**Comment by fhunleth** [comment]
The firmware update process doesn't write to `EXT4` partitions, so I think something else is wrong. The official Nerves images handle partial upgrades fine, so while I'm not sure what's happening, I think there's something else going on in your system or configuration that somehow is associated with the upload.

Have you modified the `fwup.conf` at all?

**Comment by trarbr** [comment]
Well, I don't know... it might have been EXT3? Anyway, with the changes in PR #45 I am unable to reproduce the issue. I don't know if this is the right way to fix it 🤷‍♂ but it does work in my case.

We use a modified `fwup.conf` compared to the base Nerves system, but this particular upgrade had no fwup-related changes.

**Comment by fhunleth** [comment]
We only use SquashFS and FAT. Ext4 is on the application partition which should be unmodified by `fwup`, unless you've modified the `fwup.conf`. If you increased root filesystem partitions, maybe they're overwriting the application partition? I only mention since I've seen Ext4 recover from some overwrites and not others - both impressive and kind of scary that it could exist undetected.

**Comment by trarbr** [comment]
We updated our system to use version 0.4.4 of `nerves_firmware_ssh` and I can no longer reproduce this issue 🍾  Many thanks for the quick response ❤️
