### ISSUE TITLE
Error with ssh

### ISSUE THREAD

**Issue by ckr123** [nerves-project/nerves_firmware_ssh#8]
SSH is working for a while then it suddenly stops and i get this error.

```
fwup: Upgrading the B partition
 1%** (MatchError) no match of right hand side value: {:error, :closed}
   lib/mix/tasks/firmware.push.ex:130: Mix.Tasks.Firmware.Push.wait_for_complete/3
   (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
   (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
   (elixir) lib/code.ex:376: Code.require_file/2
```

**Comment by fhunleth** [comment]
I think that we should be able to reproduce this error. Could you post your Nerves system and version as well?

**Comment by ckr123** [comment]
`nerves "0.7.5`
`nerves_system_rpi3, "0.16.1`
`nerves_system_br, "0.13.9"`
`nerves_runtime, "0.4.4"`

**Comment by fhunleth** [comment]
Update: #9 addresses this issue, but I can't merge it for a few reasons unfortunately. I'll try to clean it up this coming week.

**Comment by fhunleth** [comment]
#12 combined with an update to `fwup` that supports the new handshake will make it possible to see what error you're getting that's failing the firmware update. I suspect that we'll either run into the error when going through the release process for the RPi3 or your updating everything will fix whatever inconsistency there was. In either case, I'll post again after the changes have been reviewed and releases are made.

**Comment by fhunleth** [comment]
This was fixed with the `fwup` handshake feature as stated above. I missed closing this issue when the previous release was made.
